FROM ubuntu
MAINTAINER Giovanni DallOlio <dalloliogm@gmail.com>

RUN apt-get install -y wget git 
RUN git clone git@github.com:smilefreak/selectionTools.git


#RUN wget http://downloads.sourceforge.net/project/samtools/tabix/tabix-0.2.6.tar.bz2?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fsamtools%2Ffiles%2Ftabix%2F&ts=1426198744&use_mirror=garr
#
#tabix ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz 22:23862589-25055718 > myregion.vcf

